enables Beatmaps to be written back to .osu files
llllllllll/slider pull request #101
Opened 2022-03-20 13:21 UTC by IMXZ1234

``pack`` function is added for ``HitObject`` and ``Curve`` as well. Written ``.osu`` has been tested and can be recognized and played by osu! client.
``Colours`` section in ``.osu`` file is omitted since slider does not parse this section. Support for parsing colours may be added in the future, so the generated ``.osu`` can include this section. Default values are chosen to be the same as those used by the Beatmap editor which is embeded in osu! client.

2022-03-20 13:25 UTC, IMXZ1234 commented
However, during the test of the generated ``.osu`` file, all HitObjects are interpreted as in a single combo. I think the problem is with the parsing phase. When parsing HitObjects, combo information which is saved together  in one ``int`` with hit object type_code is dropped. This may be fixed perhaps by adding extra ``is_new_combo`` and ``combo_colour`` member to ``HitObject`` to record the combo information.

2022-03-20 17:55 UTC, tybug commented
Before I take a look at this, can you fix the inspection errors? (you might want to lint locally with flake8 instead of pushing to test; from experience, fixing one inspection often causes another to pop up). Github made me manually approve the workflows to run on this pr since you're a first time contributor, which is why it didn't run when you first opened the PR.

2022-03-21 02:54 UTC, IMXZ1234 commented
Inspection errors are all `E501 line too long`, now fixed. Also included a few minor changes: 

1. Shorten the function name `_replace_invalid_with_default` to `_invalid_to_default`.
2. Prevent `Bookmarks` field in `Editor` section from appearing in generated `.osu` file if it is an empty list.

2022-03-21 04:46 UTC, IMXZ1234 commented
I believe the problem in my former review boils down to this:
Using default test beatmap `AKINO from bless4 & CHiCO with HoneyWorks - MIIRO vs. Ai no Scenario (monstrata) [Tatoe].osu`,
Simply add a test in `slider/tests/test_beatmap.py` like this:
```
def test_parse(beatmap):
    print(beatmap.hit_objects()[12])
```
the result will be:
```
<Circle: Position(x=52.647999999999996, y=201.648), 4923ms>
```
While in the original `.osu` file the line recording this hit object is:
```
49,198,4923,5,0,2:0:0:0:
```
Position is incorrect.

2022-03-21 05:09 UTC, IMXZ1234 commented
Now I learn the problem can be solved by setting the `stacking` parameter of `Beatmap.hit_objects()` to `False` to disable the `_resolve_stacking` function turned on by default.

2022-03-25 01:39 UTC, tybug commented
I don't think `stacking=False` would be a good default. Even ignoring the fact that changing it would be a breaking change, most uses of slider want the position of the hitobject as it would appear in gameplay, which is what stacking provides.

2022-03-25 01:50 UTC, tybug requested changes

2022-03-25 01:50 UTC, tybug commented on slider/position.py
> +        return int(self.x) == int(other.x) and int(self.y) == int(other.y)
unless you have a good reason for it, I don't think this should exist

2022-03-25 01:50 UTC, tybug commented on slider/beatmap.py
> +        for hit_object in self._hit_objects:
any reason not to use `self.hit_objects(stacking=False)` here?

2022-03-25 01:50 UTC, tybug commented on slider/tests/test_beatmap.py
> +def test_pack(beatmap):
even for testing code, this is...a mess. I can barely read this code with all the line continuation characters. Either variable names need to be shortened or nesting needs to be reduced (ie code pulled out of the loop).

First though, I would say that we shouldn't be checking against `beatmap.__dict__`, but instead against each attribute explicitly. Something like...

```python
for attr in ["audio_filename", "audio_lead_in", "preview_time", ...]:
    assert gettattr(beatmap, attr) == getattr(packed_beatmap, attr)
```

with special case attributes (like hitobjects) handled separately.

2022-03-25 01:50 UTC, tybug commented on slider/tests/test_beatmap.py
> +                        hit_object.__dict__.items():
similarly here, accessing `__dict__` makes this code harder to read, not easier. Just explicitly assert that the fields you want to be equal are equal.

2022-03-25 05:39 UTC, IMXZ1234 commented
I had written `tests.test_beatmap.test_pack()` as a draft script rather than a piece of code, without taking its readability into consideration. My fault. Now it has been refined.
Since `Beatmap#pack` is a member method, I think it is all right to directly access the private member `_hit_objects`. Also, it promotes efficiency since 'self.hit_objects(stacking=False)' does quite a number of checks inside it and actually constructs a new tuple on its return. Thus I presume it's better to use `_hit_objects` instead.

2022-03-25 16:22 UTC, tybug commented
please don't force push if you can absolutely avoid it. It messes up the history of anyone who has checked out this pr (ie, me).

2022-03-25 16:27 UTC, tybug commented
> Since pack() is a member method, I suppose directly accessing the private member _hit_objects is all right. Also, it promotes efficiency since self.hit_objects(stacking=False) does quite a number of checks inside and actually constructs a new tuple on its return. Thus I suppose it would be better to use _hit_objects instead.

generally I prefer accessing known apis (ie `self.hit_objects()`) where possible, even inside member methods. But on second thought this is actually probably better since you really do want the "raw" representation of the hitobjects, since you're about to write them back to a .osu file.

2022-03-26 01:35 UTC, IMXZ1234 commented
> which only catches the case of "tp1 parent none and tp2 parent not none", and not "tp1 parent not none and tp2 parent none".

Good insight.
I have no further problems.

2022-04-18 21:14 UTC, tybug commented
A few things:

* Sorry it took me so long to review this pr.

* It appears that we never parsed bookmarks properly. I've fixed this in this pr (https://github.com/llllllllll/slider/pull/101/commits/e44dd051bd7f0020880379be2ba09d0c5ec93708), and fixed the bookmark packing functionality as well (it wasn't producing correct results as it expected a list of ints and not timedeltas).

* I'm unconvinced this `pack_field` approach is the correct one, because it imposes strict requirements on the kind of functions it can accept as its third argument - it must take exactly three values; the field name, field value, and default. This means you can't add extra options to the individual pack functions like `_pack_str_list(..., separator=" ")` which is something I reached for when trying to pack bookmarks properly. But it works well enough that I'm not going to nitpick.

The largest remaining thing to do is combo colors, which as you've noted above we currently discard. I think a good path forward would be changing how we store the `type_code` for hitobjects by keeping the entire value of `type_code` from the parsed hitobject instead of just what hitobject type it is. I'll leave that for another pull, if at all.

I think this PR is good to go now. I'll wait to make sure you don't have any problems with my recent changes, and then merge.

2022-04-19 08:52 UTC, IMXZ1234 commented
I think it may be better to replace the nested function `_pack_bookmarks` with a function `_pack_timedelta_list` which is generally available.

2022-04-19 09:16 UTC, IMXZ1234 commented
Custom separators can now be used, by passing `partial(_pack_xx_list, sep=xx)` to `_pack_field`.

2022-04-24 00:58 UTC, tybug commented
still feels like an overengineered solution (re: separators), but I'm not going to fuss too much. That may also just be my bias against this functional style of programming showing. Let's get this in as-is. Thanks for the pr!

2022-04-24 00:59 UTC, merged